// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rtmgr} from '../models';
import {process} from '../models';

export function BootstrapEnvironment():Promise<void>;

export function ConsumePendingView():Promise<string>;

export function DiscoverVersions():Promise<Array<rtmgr.VersionInfo>>;

export function EnterHarness():Promise<void>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetReadyStatus():Promise<rtmgr.ReadyStatus>;

export function GetStatus():Promise<process.Status>;

export function InstallVersion(arg1:string,arg2:boolean):Promise<void>;

export function ListLocalVersions():Promise<Array<rtmgr.VersionInfo>>;

export function OpenConsoleLog():Promise<void>;

export function OpenHarnessUI():Promise<void>;

export function RestartHarness():Promise<void>;

export function ShowVersionManager():Promise<void>;

export function StartHarness():Promise<void>;

export function StopHarness():Promise<void>;

export function SwitchVersion(arg1:string):Promise<void>;
