// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapEnvironment() {
  return window['go']['main']['App']['BootstrapEnvironment']();
}

export function ConsumePendingView() {
  return window['go']['main']['App']['ConsumePendingView']();
}

export function DiscoverVersions() {
  return window['go']['main']['App']['DiscoverVersions']();
}

export function EnterHarness() {
  return window['go']['main']['App']['EnterHarness']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetReadyStatus() {
  return window['go']['main']['App']['GetReadyStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallVersion(arg1, arg2) {
  return window['go']['main']['App']['InstallVersion'](arg1, arg2);
}

export function ListLocalVersions() {
  return window['go']['main']['App']['ListLocalVersions']();
}

export function OpenConsoleLog() {
  return window['go']['main']['App']['OpenConsoleLog']();
}

export function OpenHarnessUI() {
  return window['go']['main']['App']['OpenHarnessUI']();
}

export function RestartHarness() {
  return window['go']['main']['App']['RestartHarness']();
}

export function ShowVersionManager() {
  return window['go']['main']['App']['ShowVersionManager']();
}

export function StartHarness() {
  return window['go']['main']['App']['StartHarness']();
}

export function StopHarness() {
  return window['go']['main']['App']['StopHarness']();
}

export function SwitchVersion(arg1) {
  return window['go']['main']['App']['SwitchVersion'](arg1);
}
